using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using FinPilot.Interfaces;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;

namespace FinPilot.ViewModels
{
    public partial class LoginViewModel : ObservableObject
    {
        private readonly IAuthenticationService _authService;

        // Observable properties generated by CommunityToolkit via source generators
        [ObservableProperty]
        private string _email = string.Empty;

        [ObservableProperty]
        private string _password = string.Empty;

        [ObservableProperty]
        private bool _isBusy ;

        [ObservableProperty]
        private string _errorMessage = string.Empty;

        // Dependency Injection pulls in our abstract contract automatically
        public LoginViewModel(IAuthenticationService authService)
        {
            _authService = authService;
        }

        [RelayCommand]
        private async Task LoginWithEmailAsync()
        {
            if (IsBusy) return;

            try
            {
                IsBusy = true;
                ErrorMessage = string.Empty;

                // Fire the task asynchronously against our service contract
                var user = await _authService.LoginWithEmailAsync(Email, Password);

                if (user == null)
                {
                    ErrorMessage = "Invalid email format or password (minimum 6 characters).";
                    return;
                }

                var dashboardPage = App.Current?.Windows[0].Page?.Handler?.MauiContext?.Services.GetService<Views.DashboardPage>();
                if (dashboardPage != null && App.Current?.Windows[0].Page is NavigationPage navPage)
                {
                    await navPage.PushAsync(dashboardPage);
                }

                System.Diagnostics.Debug.WriteLine($"Login successful! Welcome: {user.FullName}");
            }
            catch (Exception ex)
            {
                ErrorMessage = $"An unexpected login error occurred: {ex.Message}";
            }
            finally
            {
                IsBusy = false;
            }
        }

        [RelayCommand]
        private async Task NavigateToRegisterAsync()
        {
            var registerPage = App.Current?.Windows[0].Page?.Handler?.MauiContext?.Services.GetService<Views.RegisterPage>();
            if (registerPage != null && App.Current?.Windows[0].Page is NavigationPage navPage)
            {
                await navPage.PushAsync(registerPage);
            }
        }
    }
}

